__include__: [
  '../../../dataset/rgbtdroneperson_paired.yml',
  '../../../runtime.yml',
  '../../include/dataloader.yml',
  '../../include/optimizer.yml',
  '../../include/dfine_hgnetv2.yml',
]

output_dir: /hy-tmp/output/dfine_m_rgbtdroneperson_dual_stream

input_channels: 6
eval_spatial_size: [512, 640]

print_freq: 100
checkpoint_freq: 4

model: DFINE

DFINE:
  backbone: HGNetv2
  encoder: HybridEncoder
  decoder: DFINETransformer
  ir_identity_init: True

HGNetv2:
  name: 'B2'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True
  pretrained: False

HybridEncoder:
  in_channels: [384, 768, 1536]
  hidden_dim: 256
  depth_mult: 0.67

DFINETransformer:
  num_layers: 4
  eval_idx: -1

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00000625
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00000625
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0000625
  betas: [0.9, 0.999]
  weight_decay: 0.000125

epochs: 56

train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [512, 640]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}

      policy:
        name: stop_epoch
        epoch: 48
        ops:
          - RandomPhotometricDistort
          - RandomZoomOut
          - RandomIoUCrop

  collate_fn:
    type: BatchImageCollateFunction
    base_size: 640
    base_size_repeat: null
    stop_epoch: 48
    ema_restart_decay: 0.9999

  shuffle: True
  total_batch_size: 8
  num_workers: 4

val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [512, 640]}

  shuffle: False
  total_batch_size: 16
  num_workers: 4

use_amp: True
use_ema: True

ema:
  warmups: 0

lr_warmup_scheduler:
  warmup_duration: 0
