"""
Copyright (c) 2024 The D-FINE Authors. All Rights Reserved.

Final dual-stream RGB-T model:
  * FS-CDAE performs high-frequency-guided RGB-to-IR alignment.
  * IGMRF performs reliability-biased feature fusion.
  * MA-FDR is implemented in the decoder and consumes modal side features plus
    the reliability maps generated by IGMRF.
"""

from collections import OrderedDict
from copy import deepcopy
from typing import Dict, List

import torch
import torch.nn as nn

from ...core import register
from .multimodal_full import FSCDAELevel, IGMRFLevel

__all__ = ["DFINE"]


@register()
class DFINE(nn.Module):
    __inject__ = ["backbone", "encoder", "decoder"]

    def __init__(
        self,
        backbone: nn.Module,
        encoder: nn.Module,
        decoder: nn.Module,
        ir_identity_init: bool = True,
        use_fs_cdae: bool = False,
        use_igmrf: bool = False,
        use_ma_fdr: bool = False,
        fs_enabled_levels=None,
        fs_reduction: int = 4,
        fs_max_offset_cells: float = 1.5,
        fs_align_strength_init: float = 0.10,
        fs_align_gate_init: float = 0.10,
        fs_padding_mode: str = "border",
        fs_align_corners: bool = False,
        igmrf_attention_dim: int = 64,
        igmrf_reliability_bias_scale: float = 0.5,
        igmrf_residual_strength_init: float = 0.05,
    ):
        super().__init__()
        self.backbone_rgb = backbone
        self.backbone_ir = deepcopy(backbone)
        self.encoder = encoder
        self.decoder = decoder
        self.use_fs_cdae = bool(use_fs_cdae)
        self.use_igmrf = bool(use_igmrf)
        self.use_ma_fdr = bool(use_ma_fdr)

        return_idx = list(getattr(backbone, "return_idx", []))
        all_channels = list(getattr(backbone, "_out_channels", []))
        if not return_idx or not all_channels:
            raise AttributeError(
                "Dual-stream D-FINE requires a backbone exposing return_idx "
                "and _out_channels (HGNetv2 satisfies this requirement)."
            )
        fusion_channels = [all_channels[index] for index in return_idx]
        self.fusion_channels = fusion_channels

        if self.use_fs_cdae:
            if fs_enabled_levels is None:
                fs_enabled_levels = list(range(len(fusion_channels)))
            normalized_levels = sorted({int(level) for level in fs_enabled_levels})
            if not normalized_levels:
                raise ValueError(
                    "use_fs_cdae=True requires at least one enabled feature level."
                )
            invalid_levels = [
                level
                for level in normalized_levels
                if level < 0 or level >= len(fusion_channels)
            ]
            if invalid_levels:
                raise ValueError(
                    f"Invalid FS-CDAE levels {invalid_levels}; valid levels are "
                    f"0..{len(fusion_channels) - 1}."
                )
            self.fs_enabled_levels = tuple(normalized_levels)
            self.fs_cdae_layers = nn.ModuleDict(
                {
                    str(level): FSCDAELevel(
                        fusion_channels[level],
                        reduction=fs_reduction,
                        max_offset_cells=fs_max_offset_cells,
                        align_strength_init=fs_align_strength_init,
                        align_gate_init=fs_align_gate_init,
                        padding_mode=fs_padding_mode,
                        align_corners=fs_align_corners,
                    )
                    for level in self.fs_enabled_levels
                }
            )
        else:
            self.fs_enabled_levels = tuple()
            self.fs_cdae_layers = nn.ModuleDict()

        if self.use_igmrf:
            self.igmrf_layers = nn.ModuleList(
                [
                    IGMRFLevel(
                        channels,
                        attention_dim=igmrf_attention_dim,
                        reliability_bias_scale=igmrf_reliability_bias_scale,
                        residual_strength_init=igmrf_residual_strength_init,
                    )
                    for channels in fusion_channels
                ]
            )
            self.fusion_layers = nn.ModuleList()
        else:
            # Retain the original dual-stream baseline path for clean ablations.
            self.igmrf_layers = nn.ModuleList()
            self.fusion_layers = nn.ModuleList(
                [
                    nn.Conv2d(2 * channels, channels, kernel_size=1, bias=False)
                    for channels in fusion_channels
                ]
            )
            if ir_identity_init:
                self._init_fusion_as_ir_identity()

    @torch.no_grad()
    def _init_fusion_as_ir_identity(self) -> None:
        """Start the baseline fusion from the thermal-reference path."""
        for channels, layer in zip(self.fusion_channels, self.fusion_layers):
            layer.weight.zero_()
            index = torch.arange(channels)
            layer.weight[index, channels + index, 0, 0] = 1.0

    @staticmethod
    def _split_modalities(x: torch.Tensor):
        if x.ndim != 4 or x.shape[1] != 6:
            raise ValueError(
                f"Dual-stream D-FINE expects BCHW input with six channels "
                f"ordered as [RGB(3), IR(3)], got {tuple(x.shape)}"
            )
        return x[:, :3], x[:, 3:6]

    @staticmethod
    def _mean_diagnostics(
        diagnostics: List[Dict[str, torch.Tensor]],
    ) -> Dict[str, torch.Tensor]:
        if not diagnostics:
            return {}
        keys = sorted({key for item in diagnostics for key in item})
        result: Dict[str, torch.Tensor] = {}
        for key in keys:
            values = [item[key] for item in diagnostics if key in item]
            if values:
                result[key] = torch.stack([value.reshape(()) for value in values]).mean()
        return result

    def forward(self, x, targets=None):
        rgb, ir = self._split_modalities(x)
        rgb_features = self.backbone_rgb(rgb)
        ir_features = self.backbone_ir(ir)

        if not (len(rgb_features) == len(ir_features) == len(self.fusion_channels)):
            raise RuntimeError(
                "Backbone scale count mismatch: "
                f"RGB={len(rgb_features)}, IR={len(ir_features)}, "
                f"expected={len(self.fusion_channels)}"
            )

        fused_features: List[torch.Tensor] = []
        rgb_side_features: List[torch.Tensor] = []
        ir_side_features: List[torch.Tensor] = []
        reliability_maps: List[torch.Tensor] = []
        fs_diagnostics: List[Dict[str, torch.Tensor]] = []
        igmrf_diagnostics: List[Dict[str, torch.Tensor]] = []

        for level, (rgb_feature, ir_feature) in enumerate(zip(rgb_features, ir_features)):
            if rgb_feature.shape != ir_feature.shape:
                raise RuntimeError(
                    f"Feature shape mismatch at level {level}: "
                    f"RGB={tuple(rgb_feature.shape)}, IR={tuple(ir_feature.shape)}"
                )

            if self.use_fs_cdae and level in self.fs_enabled_levels:
                rgb_aligned, fs_diag = self.fs_cdae_layers[str(level)](
                    rgb_feature, ir_feature
                )
                fs_diagnostics.append(fs_diag)
            else:
                rgb_aligned = rgb_feature

            if self.use_igmrf:
                fused, rgb_purified, ir_purified, reliability, igmrf_diag = (
                    self.igmrf_layers[level](rgb_aligned, ir_feature)
                )
                igmrf_diagnostics.append(igmrf_diag)
            else:
                fused = self.fusion_layers[level](
                    torch.cat((rgb_aligned, ir_feature), dim=1)
                )
                rgb_purified = rgb_aligned
                ir_purified = ir_feature
                reliability = torch.full(
                    (rgb_feature.shape[0], 2, rgb_feature.shape[2], rgb_feature.shape[3]),
                    0.5,
                    device=rgb_feature.device,
                    dtype=rgb_feature.dtype,
                )

            fused_features.append(fused)
            rgb_side_features.append(rgb_purified)
            ir_side_features.append(ir_purified)
            reliability_maps.append(reliability)

        encoder_input = {
            "fused": fused_features,
            "rgb": rgb_side_features,
            "ir": ir_side_features,
            "reliability": reliability_maps,
            "diagnostics": {
                "fs": self._mean_diagnostics(fs_diagnostics),
                "igmrf": self._mean_diagnostics(igmrf_diagnostics),
            },
            "use_ma_fdr": self.use_ma_fdr,
        }
        encoded = self.encoder(encoder_input)
        out = self.decoder(encoded, targets)
        return out

    def adapt_pretrained_state_dict(
        self, pretrained_state_dict: Dict[str, torch.Tensor]
    ) -> Dict[str, torch.Tensor]:
        """Load one standard D-FINE backbone into both modality streams."""
        adapted = OrderedDict()
        for key, value in pretrained_state_dict.items():
            if key.startswith("backbone."):
                suffix = key[len("backbone.") :]
                adapted[f"backbone_rgb.{suffix}"] = value
                adapted[f"backbone_ir.{suffix}"] = value
            else:
                adapted[key] = value
        print(
            "Duplicated the pretrained single-stream backbone into the RGB and "
            "IR backbones for final dual-stream D-FINE. New FS-CDAE/IGMRF/"
            "MA-FDR parameters retain their safe identity-preserving initialization."
        )
        return adapted

    def deploy(self):
        self.eval()
        for module in self.modules():
            if hasattr(module, "convert_to_deploy"):
                module.convert_to_deploy()
        return self
